source 'https://github.com/CocoaPods/Specs.git'

platform :ios ,'11.0'
use_frameworks!
inhibit_all_warnings!

target 'WeChat' do

	pod 'Alamofire', '~> 4.9.0'
  pod 'HandyJSON', '~> 5.0.1'
	pod 'MBProgressHUD', '~> 1.1.0'
	pod 'MJRefresh','~> 3.2.0'
	pod 'Kingfisher', '~> 5.9.0'
  pod 'RxSwift', '~> 5.0.0'
  pod 'RxCocoa', '~> 5.0.0'
  pod 'Moya', '~> 13.0.0'
  pod 'SnapKit', '~> 5.0.1'
  
  pod 'YYText', '~> 1.0.7'
  pod 'YYCategories', '~> 1.0.4'
  
end
